name             'windows_dhcp'
maintainer       'Texas A&M'
maintainer_email 'derekgroh@github.com'
license          'MIT'
description      'Installs/Configures windows_dhcp'
version          '0.3.0'
supports         'windows', '>= 6.1'
depends          'windows'
